### ISSUE TITLE
Antisamy Stripping nested lists and tables

### ISSUE THREAD

**Issue by choffware** [nahsra/antisamy#23] opened 2018-04-12 22:27 UTC
If I input the following html:
```
<ul>
    <li> one </li>
    <li> two</li>
    <li> three 
          <ul>
             <li>a</li>
             <li>b</li>
          </ul>
    </li>
</ul>

The following output occurs:

<ul>
    <li> one </li>
    <li> two</li>
    <li> three 
          <ul>
          </ul>
    </li>
    <li>a</li>
    <li>b</li>
</ul>
```
Basically it moves the nested list content to the parent list.    This seems to be a bug since I can't find any configuration to fix this.

**Comment by javaarch4u** [comment] 2018-11-27 15:33
Hi @choffware! I am facing same problem, Please let me know if you were able to resolve it. Thanks in advance!

**Comment by davewichers** [comment] 2019-03-28 20:41
Hey @choffware and @javaarch4u. I can't reproduce this misbehavior in either the SAX or DOM parsers. Can you give me more details on your exact setup so I can reproduce? This is the test case I wrote to try to reproduce this:
```
    @Test
    public void testGithubIssue23() throws ScanException, PolicyException {
    	String test23 = "<ul><li>one</li><li>two</li><li>three<ul><li>a</li><li>b</li></ul></li></ul>";
    	// Issue indicates you end up with this:
    	//    <ul><li>one</li><li>two</li><li>three<ul></ul></li><li>a</li><li>b</li></ul>
    	// Meaning the <li>a</li><li>b</li> elements were moved outside of the nested <ul> list they were in    	
    	// The a.replaceAll("\\s","") is used to strip out all the whitespace in the CleanHTML so we can successfully find
    	// what we expect to find.
        assertThat(as.scan(test23, policy, AntiSamy.SAX).getCleanHTML().replaceAll("\\s",""), containsString("<ul><li>a</li>"));
        assertThat(as.scan(test23, policy, AntiSamy.DOM).getCleanHTML().replaceAll("\\s",""), containsString("<ul><li>a</li>"));
    }
```

I've actually checked in this test case into the 1.5.8 branch on github, so you can run it yourself. The 1.5.8 branch includes a bunch of library upgrades but I doubt that would have any affect on this test.

**Comment by davewichers** [comment] 2019-04-01 13:30
Given that two different people have indicated they are seeing this misbehavior, we are going to leave this open for a while. Can you guys let us know your setup that replicates this bug?

**Comment by javaarch4u** [comment] 2019-04-01 14:02
Thanks for looking in to this Dave! I appreciate it! I was actually able to identify the root cause of this problem. When there is tika parser’s dependency; boilerpipe.jar; in the classpath, antisamy loads faulty classes from boilerpipe.jar instead of nekohtml jar file. When i removed boilerpipe jar dependency from my project, everything worked as expected.

**Comment by davewichers** [comment] 2019-04-01 14:05
Thanks for the reply! And the solution to your problem. Hopefully, if @choffware sees this, he has the same or a similar issue, and can fix his setup too. I'm going to close this as its not an AntiSamy bug.

**Closed by davewichers** 2019-04-01 14:05 UTC
Labels: bug, invalid
